CREATE TABLE t1(a INTEGER, b BOOLEAN);
CREATE TABLE t2(a INTEGER, b INTEGER);
INSERT INTO t1 VALUES (1, TRUE), (2, FALSE);
INSERT INTO t2 VALUES (1, 10), (2, 20);
SELECT t1.a FROM t1 INNER JOIN t2 ON t1.a = t2.a;
--- returns:
1
2
